import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import { ScrollProgress } from "@/components/ui/scrollprogress"
import "./globals.css"
import Navbar from "@/Pages/navbar"
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html className="bg-[#09090b]" lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#09090b]`}
      >
        <div className="container mx-auto w-[50vw] ">
          <ScrollProgress />
          <Navbar />
          <div>{children}</div>
        </div>
      </body>
    </html>
  )
}
