name: Build and Deploy to Docker Hub

on:
  push:
    branches:
      - master
# dawg
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out Repo
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.PORTFOILO_USERNAME }}
        password: ${{ secrets.PORTFOLIO_PASSWORD }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: kartik200421/portfolio:latest

    - name: Verify Pushed Image
      run: docker pull kartik200421/portfolio:latest

    
          sudo docker pull kartik200421/portfolio:latest
          sudo docker stop web-app || true
          sudo docker rm web-app || true
          sudo docker run -d --name web-app -p 3005:3000 kartik200421/portfolio:latest
