name: Deploy Next.js to Docker Hub

on:
  # Trigger the workflow on pushes to the 'main' branch
  push:
    branches: ["main"]

  # Allow manual trigger from the Actions tab
  workflow_dispatch:

permissions:
  contents: read

jobs:
  # Build and push Docker image
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.PORTFOLIO_USERNAME }}
          password: ${{ secrets.PORTFOLIO_PASSWORD }}

      # Step 3: Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.PORTFOLIO_USERNAME }}/nextjs-portfolio:latest .

      # Step 4: Push the Docker image to Docker Hub
      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.PORTFOLIO_USERNAME }}/nextjs-portfolio:latest

